name: Docker Image CI (PR Build)

on:  
  push:
    branches: [ main ]

env:
  IMAGE_NAME: jenkins-docker-node

jobs:

  build:

    strategy:
      matrix:
        node-version: [ "12.13.0" ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg NODE_VERSION=${{ matrix.node-version }} --tag $IMAGE_NAME-${{ matrix.node-version }} --label "runnumber=${GITHUB_RUN_ID}"

    - name: Log in to registry       
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME-${{ matrix.node-version }}

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "main" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION