name: Docker Image CI (Publish)

on:  
  push:
    branches: [ main ]
  schedule:
    # Nightly
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:

  build:
    env:
      IMAGE_NAME: jenkins-docker-nodejs

    strategy:
      matrix:
        node-version: [ "12","14","16","latest" ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg NODE_VERSION=${{ matrix.node-version }} --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      
    - name: Log in to registry       
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=${{ matrix.node-version }}
        docker tag $IMAGE_NAME $IMAGE_ID:${{ matrix.node-version }}
        docker push $IMAGE_ID:${{ matrix.node-version }}
